# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: itenium | IT Staffing
meta-description: Your partner for all your software development needs
meta-keywords: .NET, Java, JavaScript, Node, Staffing, Software Development, Angular, React, Typescript, Belgium, BelgiÃ«
name: itenium
description: > # this means to ignore newlines until "baseurl:"
  We're here for all your IT staffing needs.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://itenium.be" # the base hostname & protocol for your site, e.g. https://example.com


feature_flags:
  freelance_jobs: true
  internal_jobs: true

# Our infos
email:
  general: info@itenium.be
  purchase: purchase@itenium.be
  gdpr: privacy@itenium.be

  # For Consultants
  timesheets: timesheet@itenium.be
  fleet: fleet@itenium.be
  onkosten-kmvergoeding: expenses@itenium.be

  # For Partners
  invoices: invoice@itenium.be
  # Jobs from partners
  requests: it-request@itenium.be
  # Payroll/consultant candidate CVs (from partner):
  jobs-partners: cv@itenium.be
  # Freelance candidate CVs (from freelancer/partner)
  freelance: vacancies@itenium.be

  # Payroll/consultant candidate CVs (from consultant):
  jobs: jobs@itenium.be

  # For Bullhorn
  crm-vacancy: vacancy@itenium.be
  crm-contact: contact@itenium.be
  crm-company: company@itenium.be
  crm-placement: placement@itenium.be
  crm-candidate-permanent: candidate-permanent@itenium.be
  crm-candidate-contract: candidate-contract@itenium.be


address:
  maatschappelijk: Pilatusveld 7, 1840 Londerzeel
  office:
    street: Mechelsesteenweg 200
    locality: Sint-Katelijne-Waver
    postalCode: 2860
    region: Vlaanderen
  googleMaps: https://www.google.com/maps/place/itenium/@51.0499162,4.5108556,17z/data=!3m1!4b1!4m5!3m4!1s0x0:0x28e71d05f3564159!8m2!3d51.0499162!4d4.5130443

tel: +32 15 79 46 89

btw: BE0687800967
bank: BE84 7370 4817 1859
bic: KREDBEBB
bank_name: KBC
paritair_comite: PC200
rsz_nr: 210-1968439-42

privacy_statement_last_revision: 31/05/2021


# Social
google_analytics:
twitter_username: itenium_be
github_username: itenium-be
linkedin_company: itenium
instagram: itenium
facebook: itenium.be
youtube: "@iteniumconsultancy"


# Blog
github_data_url: https://github.com/itenium-be/blog-posts/blob/master
collections:
  posts:
    output: true
    permalink: /blog/:categories/:title/

# Build settings
markdown: kramdown

# highlighter: We've implemented highlightjs manually
kramdown:
  syntax_highlighter_opts:
    disable : true

# https://github.com/jekyll/jekyll-paginate
paginate: 8
paginate_path: /blog/page:num/

# https://github.com/jekyll/minima
# bundle show minima
theme: minima

# https://pages.github.com/versions/
#   - jekyll-feed # https://github.com/jekyll/jekyll-feed
plugins:
  - jekyll-paginate
  - jemoji # https://github.com/jekyll/jemoji
  - jekyll-gist # https://github.com/jekyll/jekyll-gist
  - jekyll-avatar # https://github.com/benbalter/jekyll-avatar
  - jekyll-redirect-from # https://github.com/jekyll/jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
