# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: itenium | .NET consulting
meta-description: .NET JavaScript Consultancy Software Development Typescript Belgie
name: itenium
email: info@itenium.be
jobemail: jobs@itenium.be
address: Linde 11, 1840 Londerzeel
tel: +32 477 54 89 57
description: > # this means to ignore newlines until "baseurl:"
  We're here for all your software consultancy needs.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://itenium.be" # the base hostname & protocol for your site, e.g. http://example.com

btw: BE0687800967

bank: BE84 7370 4817 1859
bic: KREDBEBB
bank_name: KBC
paritair_comite: PC200

google_analytics: UA-107324319-1
twitter_username: itenium_be
github_username: itenium-be
linkedin_company: itenium

# Display links to the jobs page?
display_jobs: true

github_data_url: https://github.com/itenium-be/blog-posts/blob/master

collections:
  posts:
    output: true
    permalink: /blog/:categories/:title/

# Build settings
markdown: kramdown

# highlighter: none
kramdown:
  syntax_highlighter_opts:
    disable : true

theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
